### ISSUE TITLE
Epic: Build, package, and manage execution of cri-dockerd

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1137]
Starting with 1.24 there will no longer be any `--docker` support in `k3s`. We will need to manage `cri-dockerd` ourselves and pass `--container-runtime-endpoint=unix:///var/run/cri-dockerd.sock` instead.

- [x] Build cri-dockerd
- [x] Package cri-dockerd in alpine-lima
- [x] Package cri-dockerd in wsl-distro
- [x] Manage cri-dockerd via openrc from Rancher Desktop

**Comment by Nino-K** [comment]
After a discussion with @jandubois we are good to pull the release binary from [cri-dockerd](https://github.com/Mirantis/cri-dockerd/releases)

**Comment by jandubois** [comment]
Look at the systemd units to figure out what to put into the corresponding openrc file: https://github.com/Mirantis/cri-dockerd/tree/master/packaging/systemd

**Comment by Nino-K** [comment]
https://github.com/lima-vm/alpine-lima/pull/50
https://github.com/rancher-sandbox/rancher-desktop-wsl-distro/pull/33

**Comment by jandubois** [comment]
Fixed by #1766
