### ISSUE TITLE
Epic: Rancher Dashboard Integration

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#1192]
### Problem Description

Bundle Rancher Dashboard along with Rancher Desktop

### Proposed Solution

- [x] #1271
- [x] #1272
- [x] Start Steve on launch with currently selected Kuberneted Context
- [x] Create menu item for accessing Rancher Dashboard
- [x] Render Rancher Dashboard through electron web embed
- [x] #1364
- [x] #1365
- [x] #1216

### Additional Information

- https://www.electronjs.org/docs/latest/tutorial/web-embeds
- https://github.com/rancher/steve
