### ISSUE TITLE
Epic: RD must work without sudo (on macOS)

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1224]
This is an extended version of #1127:

We have 3 different levels of users:

1. Regular users without access to `sudo` (or don't want to use it)
2. Users with sudo access requiring a password
3. Users with password-less sudo by default

`sudo` is required for the following operations:

* install vmnet related binaries into `/opt/rancher-desktop`
* create `/etc/sudoers.d/rancher-desktop-lima`
* start lima instance using a vmnet instance
* overwrite `/var/run/docker.sock`
* create symlinks in `/usr/local/bin` (see #1155)

Right now setting up and using vmnet is not optional, so it is impossible to run Rancher Desktop at all without `sudo`.

Tasks:

* [ ] Make `sudo` usage configurable
* [ ] Don't configure `vmnet` networks when `sudo` is unavailable (also no `/opt/rancher-desktop`, and no sudoers file)
* [ ] Show how to use the docker socket from the "internal" location
* [ ] Verify that RD works when installed into `$HOME/Applications`
* [ ] Provide alternate mechanism to put utilities on the `PATH` without `sudo`
* [ ] Don't show `sudo` prompts to users with password-less `sudo`

**Comment by pboushy** [comment]
> `sudo` is required for the following operations:
> 
> * install vmnet related binaries into `/opt/rancher-desktop`
> * create `/etc/sudoers.d/rancher-desktop-lima`
> * start lima instance using a vmnet instance
> * overwrite `/var/run/docker.sock`
> * create symlinks in `/usr/local/bin`

I'm the Mac enterprise administrator for my company, and looking at Rancher Desktop to replace Docker Desktop on a few hundred systems. Here's my preferred mechanism for most of this:

It would be ideal for these items to be rolled up into a PKG, that either Rancher Desktop installs when it doesn't detect them (if user is admin) OR that an admin can install as part of providing Rancher Desktop to non-admins.

As Mac Admins, we use tools like Jamf Pro, VMWare's Workspace One, or Munki to provide software to our employees.
Those tools have the ability to deploy Rancher Desktop, and immediately following install the "support utilities PKG"
This would also allow mass deployment with minimal config required from developers.

**Comment by drenze-athene** [comment]
> I'm the Mac enterprise administrator for my company, and looking at Rancher Desktop to replace Docker Desktop on a few hundred systems. Here's my preferred mechanism for most of this:
> 
> It would be ideal for these items to be rolled up into a PKG, that either Rancher Desktop installs when it doesn't detect them (if user is admin) OR that an admin can install as part of providing Rancher Desktop to non-admins.
> 
> As Mac Admins, we use tools like Jamf Pro, VMWare's Workspace One, or Munki to provide software to our employees. Those tools have the ability to deploy Rancher Desktop, and immediately following install the "support utilities PKG" This would also allow mass deployment with minimal config required from developers.

As a user in an Enterprise environment who has admin access to his Mac workstation, this would also be a preferred method for me. I currently have to provide my admin password each time RD starts, and it's a PITN.

**Comment by scrudge** [comment]
I'm facing the same issue.  I have sudo previleges but my IT dept adds this to the bottom of the sudoers file

`Defaults timestamp_timeout=0
%_cyberarkepm_sudoers ALL = (ALL) PASSWD: ALL
##` 

so RD fails to handle the sudo prompt.

**Comment by 589290** [comment]
Installing RD via direct download fails on my enterprise laptop since my user is not a local admin and I have limited sudo priviledges. However, I can at least complete the install with `brew` from: https://formulae.brew.sh/cask/rancher since it prompts me to enter a `sudo` password twice before the `brew` install completes successfully.

```
user@box:~/x$ brew install --cask rancher
==> Downloading https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.1.1/Rancher.Desktop-1.1.1.x86_64.dmg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/306701996/ee719414-9ecd-4d61-bfa6-7d9adbe00891?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-
######################################################################## 100.0%
==> Installing Cask rancher
==> Moving App 'Rancher Desktop.app' to '/Applications/Rancher Desktop.app'
Password:                   
Password:                   
🍺  rancher was successfully installed!
```

However, it looks like RD is still unable to create certain VM resources with Lima:
![Screen Shot 2022-03-13 at 10 04 10 AM](https://user-images.githubusercontent.com/69643994/158066072-66da93f0-a42a-4e50-881d-9b5e175f2106.jpg)

```
Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
```
```
level=info msg="Terminal is not available, proceeding without opening an editor"
level=info msg="Starting switch daemon for \"shared\" network"
level=fatal msg="failed to run [sudo --user root --group wheel --non-interactive /bin/mkdir -m 775 -p /private/var/run/rancher-desktop-lima]: stdout=\"Approval Required: You are about to run this Sudo Command with administrative privileges. Please enter your password and press OK to proceed.\\n\", stderr=\"sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper\\n\": exit status 1"
limactl start --tty=false /Users/user/Library/Application Support/rancher-desktop/lima/_config/0.yaml
Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8692)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

**Comment by jandubois** [comment]
@pboushy offered on Slack:

>I build alot of scripts and stuff to generate PKGs for custom packages we have. Let me know if there’s anything I can do to help y’all with that. I also have some experience with privileged helpers that would allow a normal user to run Rancher Desktop and Rancher Desktop create those items.

cc/ @mook-as

**Comment by ricbar3** [comment]
> I'm facing the same issue. I have sudo previleges but my IT dept adds this to the bottom of the sudoers file
> 
> `Defaults timestamp_timeout=0 %_cyberarkepm_sudoers ALL = (ALL) PASSWD: ALL ##`
> 
> so RD fails to handle the sudo prompt.

I am running into this issue as well with the newest version of RD and M1 Macbook 14.3 

Seems tied to the sudo no password

'0'
],
stdout: '',
stderr: 'time="2024-02-11T19:29:31Z" level=info msg="Using the existing instance \\"0\\""\n' +
'time="2024-02-11T19:29:31Z" level=info msg="Starting vde_switch daemon for \\"rancher-desktop-shared\\" network"\n' +
'time="2024-02-11T19:29:31Z" level=fatal msg="failed to run [sudo --user root --group wheel --non-interactive /bin/mkdir -m 775 -p /private/var/run]: stdout=\\"\\", stderr=\\"sudo: a password is required\\\\n\\": exit status 1"\n',
code: 1,
[Symbol(child-process.command)]: '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura start --tty=false 0'
}

Has there been any movement on this issue being fixed?

**Comment by fethiarras** [comment]
Hi,

I made an Enhancement Request to CyberARK for supporting --non-interactive on EPM. Since agent 24.7, you need to open a case to CyberARK, if you want activate the support of --non-interactive and it's work :)
