### ISSUE TITLE
Epic: Getting the "settings" interface to v1

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1925]
We are moving towards a "transaction" model for applying settings changes. See #1654 for the discussion about the GUI implications: settings changes are local to the UI until the user presses an "Apply" button which will send a settings-change request to the `rd-engine` to move the current state to the desired state in the most efficient manner possible.

The `rdctl set` command should invoke exactly the same function on the engine.

Tasks:

* [ ] Create a list of all settings (current, and in the future):
       #1924 

* [x] #1926

* [ ] Implement settings API in rd-engine

* [ ] Use new settings API from the GUI
        #1654 

* [ ] Update commandline parameters to use the new settings names

* [ ] Update `rdctl set` and `rdctl start` commands to use the new API and names

* [x] #1935
