### ISSUE TITLE
Epic: Backend Refactoring (splitting out K8s)

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#1997]
We want to refactor the [`KubernetesBackend`](https://github.com/rancher-sandbox/rancher-desktop/blob/096181dd764b4f4fd2b8158bee8698f3a14213e7/src/k8s-engine/k8s.ts#L106) related code to have a cleaner split between things that deal with the VM / runtime environment, and things involved in running Kubernetes.  This is to make code dealing with disabling Kubernetes to be cleaner, as well as to limit the responsibility of each portion of code.  It is also to help with follow-up work to use REST APIs for the UI.

This will need to consider the parallel work done in #1793 and related (where we split out the integration code), as well as the efforts around CLI / REST API (#1748, #1896).

Involved tasks:
- [x] #2160
  - Use state changed events to mange helper processes lifetimes.
- [x] #2267
- [x] #2266
- [x] Rename `KubernetesBackend` to `VMBackend`
- [x] Add ability to execute commands to `VMBackend` (or other interface only exposed to `KubernetesBackend`)
- [x] Create new `KubernetesBackend` interface
  - Callers still use `VMBackend`; it is just internally forwarded to `KubernetesBackend`
  - [ ] Implement `KuberentesBackend` for WSL
  - [ ] Implement `KubernetesBackend` for Lima
- [x] Remove forwarding in `VMBackend`, main code uses `KubernetesBackend` directly.
- [ ] File follow-up epic to transition UI to use REST APIs

**Comment by mook-as** [comment]
Moved immutable configuration up to better align with other plans.

**Comment by mook-as** [comment]
FWIW, work has been ongoing in the [mook-as/refactor](https://github.com/mook-as/rd/commits/refactor) branch (with various PRs already submitted from that branch).

**Comment by mook-as** [comment]
The refactoring has been complete.
