### ISSUE TITLE
Epic: Fork cri-dockerd and apply fix to metrics performance problem

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2022]
See #2012 for details

Tasks

* [X] Fork https://github.com/Mirantis/cri-dockerd into `rancher-sandbox` org
* [X] Apply https://github.com/Mirantis/cri-dockerd/pull/38 in a branch
* [X] Create GH action to build a release (maybe can re-use what already exists); strip symbols etc to shrink image
* [X] Tag and create release
* [X] Update https://github.com/lima-vm/alpine-lima and https://github.com/rancher-sandbox/rancher-desktop-wsl-distro to use the release from the fork instead of upstream

**Comment by jandubois** [comment]
Fixed by #2085
