### ISSUE TITLE
Epic: Developer/Technical Details Docs

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#2273]
The purpose of this epic is to develop a set of developer/technical details docs focusing on the internal workings of Rancher Desktop. The intended audience for these docs would be new developers/contributors to the project,  and anyone who is interested to know what's under the hood, and how things work internally etc.

Below is the first list of docs. As we work on developing these docs, we can split the items further into sub tasks, or combine items wherever applicable.

Overview

- [ ] Architecture/Component Diagram

  An extension of the diagram on the rancherdesktop.io homepage with more details. Capture all the components running on the 
  host and in the VM, with a brief note about each component's

- [ ] High level code walkthrough video

  A high level walkthrough to describe the code organization. The purpose is to help people in knowing where to start to add/fix things in Rancher Desktop.

- [ ] Feature Workflows

  Purpose of Feature workflow is to describe what happens in the background for different UI operations we support. Wherever 
  possible, pointing to the scripts, functions that are invoked as part of an operation helps.
  

  - [ ]   App Launch Flow
  - [ ]   App shutdown Flow
  - [ ]   Container runtime switch
  - [ ]   Kubernetes version change
  - [ ]   Reset Kubernetes
  - [ ]   Reset Kubernetes & Images
  - [ ]   Factory Reset
  - [ ]   Uninstallation flow
  - [ ]   In App upgrade flow

- [ ] Advanced Topics

  - [ ] Rancher Desktop Distro Overview
         What does RD distro contain? Process to update the distro and release a new version.
  - [ ] Networking Deep dive
         How does Rancher Desktop enable networking? For example, Between host and VM, How does DNS resolution happen etc.
