### ISSUE TITLE
Epic: Create diagnostics page

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2319]
Stories, ordered so we have a working PoC as soon as possible:

- [x] #2655
- [x] #2783
- [ ] #2805
- [x] #2656
- [ ] Add "fix action" callback to sample checks
- [ ] Update UI to support fix actions that may update the diagnostics object
- [ ] Create more comprehensive body of checks
- [x] #2913

There are several checks we could do automatically to verify that the local system is configured properly:

* Are the bundled utilities accessible from a user's shell?
* Are the files under `~/.docker/cli-plugins` symlinks to `~/.rd/bin`?
* Has the docker context been set to `rancher-desktop` (or not present, if the symlink in `/var/run/docker.sock` is in place)?
* Is the current kubectl context set to `rancher-desktop`?
* Is the API endpoint responding properly (docker socket on the host, containerd socket inside the VM, k3s socket on the host)
* (macOS) Is the external cluster IP on the bridged network?
* Does the host have an active internet connection (to pull k3s versions, and container images)?
* Is the docker-credential-* helper configured and working? Make sure it is not set to `none`.
* Are the log files growing beyond a reasonable size?
* Are we almost out of space inside the data volume?

This is just an initial brain-dump; there are probably more.

Any problems found should also display instructions how to debug this further and/or how to fix this.

See also `brew doctor` for other software providing a similar tool (but from the CLI).

**Comment by rak-phillip** [comment]
This might be related to #1217

**Comment by gaktive** [comment]
The "Run Diagnostics" command would be data driven so this could also be logged somewhere for a feature like a support bundle whereby people can easily spot errors.

**Comment by jandubois** [comment]
Moving this Epic to the following milestone.

Normally I would close it, and create a new one for the next release cycle, but this one has open issues referencing it, and I want to retain this information (for now).

**Comment by jandubois** [comment]
Ideas for additional checks have been moved to discussion in #3157.

We'll create a new epic for adding "fix actions" and other diagnostic improvements in the future.
