### ISSUE TITLE
Epic: Modal Preferences Backend

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#2362]
We have plans for making setting changes atomic (that is, have an `Apply` button that applies all settings in one go).  There needs to be some backend changes to make this happen:

* [x] Verify that all application settings are applied correctly with just the settings toggle
  * [ ] Linux/Mac: path management
  * [ ] Windows: WSL integrations
    * Maybe drop the `k8s-integrations` / `k8s-integration-set` IPC topics
* [x] #2370
  * [x] #2366
  * [x] #2419
  * [x] #2586 
  * [x] #2500
* [x] #2390
  * [x] KubernetesBackend: add method to check (given a Setting) if the backend is out of sync.
  * [x] WSL: Restart if settings changed after starting
  * [x] Lima: Restart if settings changed after starting 

### Bugs

* [x] #2509

### Follow ups
* [ ] #2540

See also: #2373 for the matching UI.

**Comment by jandubois** [comment]
#2540 will be dealt with separately
