### ISSUE TITLE
Epic: Support private registries

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2401]
This is a followup to #1277 that provided credential helpers on the host for moby/docker and the credentials forwarder for nerdctl/containerd.

Missing functionality:

- [ ] #2320
- [ ] #2321
- [ ] #1850 (assigned to @jandubois)
- [ ] Create symlink for client certs on Windows too
- [ ] configure /var/lib/kubelet/config.json
- [ ] integration tests for credential helpers and forwarder
