### ISSUE TITLE
Epic: Published ports in WSL should map correctly on the host side

### ISSUE THREAD

**Issue by Nino-K** [rancher-sandbox/rancher-desktop#2677]
### Problem Description

As reported by some of our [users](https://github.com/rancher-sandbox/rancher-desktop/issues/1180) the port mapping in wsl only happens on `127.0.0.1`. This behavior needs to align with dockers `-p` argument. If no address is provided e.g 
```
docker run -d --name test-nginx -p 38080:80 nginx
```
The port mapping should take place on all interfaces or `INADDR_ANY`. However, the user can optionally provide an IP address e.g 
```
docker run -p 127.0.0.1:38080:80
```
Which should only attach the given port on the localhost on the host side. 

### Proposed Solution

The proposed solution requires an additional privileged process (Supervisor) to run on the host to mirror the above behavior. 
This process can receive port mapping information for both containerd and kubernetes from [Rancher Desktop Agent](https://github.com/rancher-sandbox/rancher-desktop-agent). However, docker port mappings are not exposed through the agent and must be incorporated in the `rancher-desktop-agent` or via `wsl-helper` (TBD).

### Additional Information

Tasks:

- [x] Update RD Agent to retrieve docker published port data [PR 8](https://github.com/rancher-sandbox/rancher-desktop-agent/pull/8) and [PR 9](https://github.com/rancher-sandbox/rancher-desktop-agent/pull/9)
- [x] Update RD Agent to monitor and publish containerd publish ports
- [x] Create a privileges service (Supervisor) that runs on the host https://github.com/rancher-sandbox/rancher-desktop/pull/2727
- [x] Create documentation for Supervisor
- [x] Change Vtunnel to support named pipes
- [x] Register the RD Agent with Vtunnel to be able to send events to the host
- [x] Register the Supervisor with Vtunnel to receive published port events via named pipes
- [x] Incorporate the Supervisor process in the RD to gain admin control during installation of RD
- [x] Create an installer for Supervisor
- [x] Error management, if port mapping comments on docker or nerdclt fail to display a friendly message to the user(this could potentially be a [windows tile notification](https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast-desktop-cpp-wrl) due to the lack)

**Comment by Nino-K** [comment]
https://github.com/rancher-sandbox/rancher-desktop/pull/2959
