### ISSUE TITLE
Epic: Improve BATS tests

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3026]
* [ ] Use full path for all commands (like `$RDCTL`)
* [ ] Verify BATS works on WSL2 using Linux utilities
* [ ] Add Windows support to BATS using Win32 utilities
* [ ] Package BATS tests in Github Action
* [ ] Document all BATS tests
* [ ] Document all environment variables used to configure BATS
* [ ] Run BATS in Github Actions

* [ ] Create an epic for `rdctl` improvements for BATS
  - Provide all required path locations (`LIMA_HOME`, `settings.json`) etc
  - Move the whole factory reset logic to rdctl (see also #2957)
