### ISSUE TITLE
Epic: Improve diagnostics feature

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3063]
This epics builds on the work of #2319. It is explicitly **not** about adding additional diagnostics, which should be independent enhancement requests, but about improving the capabilities of the mechanism itself.

* [ ] Review diagnostics and develop guidelines for creating new ones
* [ ] Design the "Fix action" UI
* [ ] Allow display of passing diagnostics
* [ ] #3000 
* [ ] #3005
