### ISSUE TITLE
Epic: Image Allow List

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3236]
This epic covers the initial Image Allow List (IAL) feature:

<img width="431" alt="Screen Shot 2022-10-13 at 9 30 33 AM" src="https://user-images.githubusercontent.com/78947/196293530-3d66398d-8677-4cc7-8334-3ee8e0718fdf.png">

When enabled, any image pulled from by the container engine must match one of the rules; otherwise it is being rejected.

* [x] #3245
* [x] https://github.com/rancher/dashboard/issues/7325
* [x] #3333
* [x] Add OpenResty and mkcerts to wsl-distro
* [x] Add OpenResty and mkcert to rancher-desktop distro for use by Lima
* [x] Install OpenResty and mkcert in Lima VM from host mount
* [x] Configure OpenResty with image-allow.lua script when enabled
* [x] Enable `dockerd` to use OpenResty proxy
* [x] Enable `containerd` to use OpenResty proxy
* [x] Document Image-Allow-List preference page

Further enhancements to the Image Allow List feature are tracked in #3237

Acceptance criteria (containerd support may be missing though):

* User can enable/disable IAL in Preferences
* User can add/remove patterns in IAL (when it is enabled)
* IAL is persisted in settings
* When IAL is disabled, any images can be pulled with both docker/nerdctl and kubernetes
* When IAL is enabled, images matching any pattern can still be pulled
* When IAL is enabled, images not matching any pattern will be blocked
* When an image is blocked, the user will get a proper explanation in the `docker pull` output
* When an image is blocked, the user will get a proper explanation in the pod event log
* Even when IAL is enabled, the user can create an image locally that does not match any pattern on the IAL.
* IAL does not allow adding duplicate patterns (determine case-insensitively), including creating a duplicate by editing.
* If the UI rejects a user action (like adding a duplicate), it should display an explanation.
* When IAL is enabled and the user tries to pull a non-matching image via the Image UI, the error message is clearly visible in the log output.

Additional acceptance criteric if admin IAL are implemented:

* The IAL is enabled and locked when the admin IAL exists and the patterns show the content of the admin list
* When IAL is locked, UI displays a lock icon with a tooltip explaining why it is locked.
* The user can neither disable nor edit the IAL
* The "when IAL is enabled" criteria above apply, checking against the admin patterns

Automated testing:

* @torchiaf to look into unit tests for the UI part
* There is already an E2E test to make sure the new tab exists

**Comment by gaktive** [comment]
Closing in light of a continued epic #3237
