### ISSUE TITLE
Epic: Image Allow List Enhancements

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3237]
Continues the work from #3236 

* [ ] Add a pattern tester to check a sample image name against all patterns
* [ ] Add code to "Image Pull" to check against the allow list, when enabled
* [ ] Implement support for filtering registries by IP address

Example UI for image tester:

<img width="424" alt="Screen Shot 2022-10-13 at 9 30 47 AM" src="https://user-images.githubusercontent.com/78947/196293650-1117afb2-6708-4d98-9042-3bd9928dffcf.png">
