### ISSUE TITLE
Epic: Windows Installer

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#3309]
This epic is spawn off #3104 and will convert the Rancher Desktop installer on Windows into using Windows Installer (msiexec).

- [x] Build `Rancher Desktop Setup.msi` 
  - [x] Uninstall NSIS-based Rancher Desktop (<= 1.6.x) if installed
    - #3318
  - [x] Option to install in privileged mode (via normal UAC prompt):
    - #3310
    - [x] Install in Program Files
      - #3310 
    - [x] Installs WSL as necessary
      - #3402
    - [x] Add Rancher Desktop to system PATH
      - #3324
    - [x] Install RD Privileged Service
      - #3359
    - [x] Uninstaller needs to remove RD Privileged Service
      - #3359
    - [x] Uninstaller needs to remove from system PATH
      - #3324
  - [x] Option to install unprivileged (user cancels UAC prompt):
    - #3310
    - [x] Install in ~/AppData/Local/Programs (this is automatic)
    - [x] Add Rancher Desktop to user PATH
      - #3324
    - [x] Uninstaller needs to remove from user PATH
      - #3324
  - [x] Add license agreement to installer. 
    - #3417
- [x] Fix the upgrader to install the MSI
  - #3388
  - [x] How do we handle elevation during auto-upgrade?
    - Supply Windows Installer property to do a system-wide install if we need to elevate. 
  - [x] Handle upgrading from older versions (need to build a setup exe that upgrades to msi)
- [x] Remove manual service install/uninstall from privileged-service.
  - Going to skip this for now; it's not actively harmful, and it's useful for dev builds / future testing.
- [x] Code signing for the new installer
  - #3418
- [x] Update documentation as required
  - https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/125

---
### Possible nice-to-haves
- [x] Reinstate run-after-installation checkbox
  - #3437 
- [x] Stop using default Wix color-scheme in the installer
  - #3507

---
### Acceptance Criteria
- Upgrading from an existing (1.6.x) install should remove the previous version automatically before installing the new version.
  - Auto-update: 1.6.x will download the exe installer (NSIS-based); that should download 1.7.0 which will look for msi installer going into 1.8.
  - Manual update: User has a choice of downloading the exe (NSIS-based) or msi (WiX-based) installer. Either should install 1.7.0, which will look for msi installers going forward.
  - Check that the old application has been removed (if the new version was installed elevated into Program Files)
    - Application no longer in `C:\Users\<>\AppData\Local\Programs\Rancher Desktop`
    - Settings, caches &c should not be touched.
  - If installed non-elevated, application still installed in `C:\Users\<>\AppData\Local\Programs\Rancher Desktop`
- Fresh install (without existing Rancher Desktop) should install correctly
  - With WSL preinstalled
  - Without WSL preinstalled
- Should only show a single elevation prompt.
  - Prompt shows SUSE publisher (not Microsoft)
- Installer should include license.
- Should not have any firewall prompts during installation or first run.
- See above re: PATH, uninstaller, privileged service.
- Check that the installer back buttons &c go to expected pages.
- Unknown if these features work:
  - Silent installation (`msiexec /quiet /i "Rancher Desktop 1.7.0.msi"`)
    - How does this interact with elevation prompt?
  - Custom installation directory (`msiexec /i "Rancher Desktop 1.7.0.msi" APPLICATIONFOLDER=C:\Path\To\Dir`)

**Comment by gaktive** [comment]
Closing. Continued work will happen in the new installer ticket #3310
