### ISSUE TITLE
Epic: Handle Kubernetes service bindings

### ISSUE THREAD

**Issue by s0nea** [rancher-sandbox/rancher-desktop#3839]
# Description
This Epic relates to the [How should we configure the guest agent service listener address](https://github.com/rancher-sandbox/rancher-desktop/discussions/3803) discussion.

The Epic is about giving users the possibility to configure the Kubernetes service bindings on Linux, Windows and MacOS.

# Stories
## Windows
- [x] Set the configuration to `0.0.0.0` by default in the guest agent
  https://github.com/rancher-sandbox/rancher-desktop/issues/3093 / https://github.com/rancher-sandbox/rancher-desktop-agent/pull/26
- [x] Add an input param to the guest agent to accept other values than `0.0.0.0`
  https://github.com/rancher-sandbox/rancher-desktop-agent/pull/27
- [x] https://github.com/rancher-sandbox/rancher-desktop/issues/3940 / https://github.com/rancher-sandbox/rancher-desktop/pull/3996

## Linux / MacOS
- [x] https://github.com/rancher-sandbox/rancher-desktop/issues/3916
- [x] #3942 - Highest Priority / https://github.com/rancher-sandbox/rancher-desktop/pull/3951
- Require `LimaAndQemu` version that contains at least Lima v0.15.0:
  - [x] Explore the current behavior and configure it to `0.0.0.0` by default (if possible) on Linux
    https://github.com/rancher-sandbox/rancher-desktop/issues/3922 
  - [x] Explore the current behavior and configure it to `0.0.0.0` by default (this is probably already the case) on MacOS
  - [x] https://github.com/rancher-sandbox/rancher-desktop/issues/3978 

<details>
<summary>Unnecessary/archived items</summary>

- Windows
  - [<s>Add a config option to the UI in order to give the user the possibility to choose between `0.0.0.0` and `127.0.0.1` https://github.com/rancher-sandbox/rancher-desktop/discussions/3803 </s>
  - <s>Investigate to expand the config option by all addresses that are bound to the host. If possible, add the option to all three platforms</s>
- Linux
  - <s>Add the possibility to choose between `0.0.0.0` and `127.0.0.1` and the corresponding config option in the UI</s>
  - <s>If possible, expand the config option by adding all addresses that are bound to the host</s>
- MacOS
  - <s>Add the possibility to choose between `0.0.0.0` and `127.0.0.1` and the corresponding config option in the UI</s>
  - <s>If possible, expand the config option by adding all addresses that are bound to the host</s>
</details>

# Acceptance Criteria
- Only users with Privileged Services installed - admin rights - will have the option to toggle between the localhost and `0.0.0.0` to bind the Kubernetes services (NodePorts and LoadBalancers). For non-admin users, these services will be available at localhost in `127.0.0.1`.

- Kubernetes service (NodePorts and LoadBalancers) bindings must be handled via `rdctl set —Kubernetes.ingress.localhost-only`. If the argument is true, Kubernetes.ingress.localhost-only must be set to true in settings.json and ingress will be available only in localhost `127.0.0.1`. If the argument is false, Kubernetes.ingress.localhost-only must be set to false in settings.json and services will be exposed to the network in `0.0.0.0`.
- Removing guest agent from Linux & MacOS must not change the current behaviours
- When Traefik is enabled, the load balancer must be attached to the correct IP address, according to what is defined in Kubernetes.ingress.localhost-only
- When services are deployed, and `Kubernetes.ingress.localhost-only=false`, node ports must be exposed.
- If user has no admin privileged, user must not be allowed to change `Kubernetes.ingress.localhost-only` via rdctl. API must return an error upon the request

# Release notes

!! Draft version !!

**Kubernetes service listener (Windows only)**

On Windows the Rancher Desktop Guestagent binds Kubernetes service listeners to 0.0.0.0 (instead of 127.0.0.1) by default, now. Furthermore there has been added a new `rdctl` configuration option `kubernetes.ingress.localhost-only` in order to reset the binding address to 127.0.0.1 again.

# Documentation
TBD

**Comment by gaktive** [comment]
At this point, https://github.com/rancher-sandbox/rancher-desktop/issues/3942 will be on target for Next (1.8.0). This epic will move to Later to handle the rest.

**Comment by s0nea** [comment]
All items of the issue are done as part of 1.8.0. Please find the follow-up issue here: https://github.com/rancher-sandbox/rancher-desktop/issues/4257
