### ISSUE TITLE
Epic: add Preferences UI for new experimental settings

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4181]
The 1.8 release adds several groups of experimental settings that can only be changed via `rdctl`. They should be exposed via the UI as well.

Settings should only be displayed on the platforms where they are applicable.

The `type` (and `use-rosetta` suboption) on macOS should go on a "Virtual Machine | Emulation" tab and memory and CPU settings should become "Virtual Machine | Hardware".

The `use-rosetta` option can only be enabled on macOS on aarch64, so should not be displayed on x86_64.

The `networking-tunnel` (on Windows) and `socket-vmnet` (on macOS) options should go on a separate "Network" tab. It will look a bit sparse for now, but we'll have more settings here in the future.

The `mount.9p` settings (on macOS and Linux) should go on a "Virtual Machine | Volumes" tab. There are 4 additional parameters that can be configured when `9p` is enabled.

```
--experimental.virtual-machine.mount.9p.cache-mode string         (Allowed values: [none, loose, fscache, mmap])
--experimental.virtual-machine.mount.9p.msize-in-kb int           maximum packet size
--experimental.virtual-machine.mount.9p.protocol-version string   (Allowed values: [9p2000, 9p2000.u, 9p2000.L])
--experimental.virtual-machine.mount.9p.security-model string     (Allowed values: [passthrough, mapped-xattr, mapped-file, none])
--experimental.virtual-machine.mount.type string                  how directories are shared (Allowed values: [reverse-sshfs, 9p, virtiofs])
--experimental.virtual-machine.networking-tunnel                  tunnel networking so it originates from the host
--experimental.virtual-machine.socket-vmnet                       use socket-vmnet instead of vde-vmnet
--experimental.virtual-machine.type string                        (Allowed values: [qemu, vz])
--experimental.virtual-machine.use-rosetta
```

## Stories

* [x] Create "WSL | Network" preferences tab for Windows https://github.com/rancher-sandbox/rancher-desktop/issues/4332
        https://github.com/rancher-sandbox/rancher-desktop/pull/4491
* [x] Create "VM | Network" preferences tab for macOS https://github.com/rancher-sandbox/rancher-desktop/issues/4334
       https://github.com/rancher-sandbox/rancher-desktop/pull/4606
* [x] Create "VM | Volumes" preference tab for macOS and Linux https://github.com/rancher-sandbox/rancher-desktop/issues/4333
        https://github.com/rancher-sandbox/rancher-desktop/pull/4537
* [x] Create "VM | Emulation" preferences tab for macOS https://github.com/rancher-sandbox/rancher-desktop/issues/4335
* [x] #4632
* [x] #4635
* [x] #4500
        https://github.com/rancher-sandbox/rancher-desktop/pull/4501
* [x] #4647 
* [x] #4667
* [x] ~~#4672~~
* [x] #4685
* [x] #4888

There is no BATS story because the experimental settings have already been implemented; this epic is purely about providing the UI for them. The acceptance tests for the settings were part of #3937, but there are no automated tests for them.

## Acceptance Criteria

* Verify the the Memory and CPU settings are now on "Virtual Machine | Hardware"
* Verify the WSL settings are now on "WSL | Integrations"
* The new tabs are displayed on their supported platforms, and hidden on the others.
* Verify the cases where the tabs are preserved across different platforms, but some of its inner options should be displayed only in their supported platfroms. e.g. virtiofs MUST NOT be available on Linux 
* All multiple choice dropdowns display the full set of options.
* 9p suboptions are hidden unless mount type is `9p`
* Rosetta suboption is hidden unless vm type is `vz`
* VM type is disabled unless running on macOS Ventura
* Verify that modified options are applied via `rdctl list-settings`
* Every tab has a help button that leads to the documentation explaining all the settings on the tab

**Comment by jandubois** [comment]
@s0nea In preparation for our meeting on Thursday, can you break down the epic into individual stories (just make a task list and convert each task into an issue)? Or let me know if you want me to do it.

Each story should be individually implemented with a separate PR, and be testable on its own. But otherwise, creating smaller stories is better than big ones.

**Comment by s0nea** [comment]
Hi @tperale ,

> This change will introduce a platform-specific tabbed settings page. Right now it's a use-case that does not exist in rancher-desktop. I pointed out a failing test that originated from platform-specific "tabbed pages".
> 
> [#4300 (comment)](https://github.com/rancher-sandbox/rancher-desktop/pull/4300#discussion_r1154492999)
> 
> I think the experimental settings page will require a change in the way tabs are handled in rancher-desktop. Let me know if I can help by any means to participate in the development of the experimental setting page.

Thank you for your hint and offering your help :slightly_smiling_face:  ! I'm wondering if it's possible to enhance/fix the tests in order to play well with platform-specific tabs?
