### ISSUE TITLE
Epic: RDX Marketplace

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#4207]
We are planning to build a Rancher Desktop Extension (RDX) Marketplace to allow for easy browsing and managing of extensions.

- [ ] List available extensions
- [ ] Display details for an extension
- [ ] Install an extension from UI
- [ ] Filter & Sort

- [ ] #4323

#### Related 

Epic: RDX Extensions #3973
