### ISSUE TITLE
Epic: Automate the port forwarding on Rancher Desktop Networking

### ISSUE THREAD

**Issue by Nino-K** [rancher-sandbox/rancher-desktop#4296]
As mentioned in this [issue](https://github.com/rancher-sandbox/rancher-desktop/issues/4096), port forwarding must be performed manually when the new experimental rancher desktop network is enabled. As part of this epic, we will be automating this process. 

- [x] Re-enable guest agent when experimental network is enabled https://github.com/rancher-sandbox/rancher-desktop/pull/4556
- [x] Allow guest agent to call the `expose` and `unexpose` API endpoint upon discovery of new publish ports (moby, containerd, k3s) https://github.com/rancher-sandbox/rancher-desktop-agent/pull/36
- [x] Configure port mappings to localhost and ports > 1024 for non-admin install
- [x] Allow traffic forwarding from loopback to the tap device inside the VM https://github.com/rancher-sandbox/rancher-desktop-networking/pull/9 
- [x] Pre-define firewall rules using wix firewall extension for admin installation. https://github.com/rancher-sandbox/rancher-desktop/issues/4686
- [x] #4596
- [x] Provide documentation to distinguish the admin and non-admin installation port mappings.https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/223
- [x] Cut a release for Guest Agent https://github.com/rancher-sandbox/rancher-desktop-agent/releases/tag/v0.3.12
- [x] Cut a release for Rancher Desktop Networking https://github.com/rancher-sandbox/rancher-desktop-networking/releases/tag/v1.1.0

# Acceptance Criteria
- Enabling the experimental networking tunnel should not change the current behaviour of the existing networking tests
- Publishing ports
- WSL integration ?
# Release notes
TBD

# Documentation
