### ISSUE TITLE
Epic: Document first-run dialog

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4327]
## Stories

* [ ] Take screenshots of first-run dialog
* [ ] Add documentation page
* [ ] Add help-button to first-run dialog
