### ISSUE TITLE
Epic: Support and improve running BATS on Windows

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#4529]
Windows-specific solutions to problems from main epic #3026 

The plan is to still always run BATs from a WSL partition, but there are still many issues to work out:

* [ ] What is `$HOME` when run from the WSL side?
* [ ] Fix other paths as in `bats/tests/helpers/paths.bash` -- every path variable needs to be worked out
* [ ] Also add the `docker` and `kuberlr` home directories
* [ ] First run: prompted for password for sudo
* [ ] README needs to specify how to update /etc/sudoers to make it passwordless

Add other issues to this list as they come up.

**Comment by mook-as** [comment]
`$HOME` is, like any other Linux, the path to your home directory (_within_ the Linux distribution; that has nothing to do with `C:\Users\<name>`).

**Comment by jandubois** [comment]
These issue have been addressed; on current `main` all tests except "traefik" and "switch-engines" are passing on Windows with both `containerd` and `moby` engines (with `RD_USING_WINDOWS_EXE`), and those remaining tests are already being worked on.

We may have additional issues when testing WSL integration (`RD_USING_WINDOWS_EXE=false`), but those should be filed as separate bugs.
