### ISSUE TITLE
Epic: Proxy support for windows.

### ISSUE THREAD

**Issue by Nino-K** [rancher-sandbox/rancher-desktop#4603]
### Problem Description

The lack of support for proxy on Windows has been a known issue on rancher-desktop, this epic is meant to address this issue. For more details please review: https://github.com/rancher-sandbox/rancher-desktop/issues/4013

- [ ] Package moproxy in `.tag.gz` to avoid bringing xz dependency into rancher-desktop, this can be either a fork of moproxy or a PR to upstream expand their support for other artifacts. 
- [ ] Fix the links to the [docs.rancher-desktop.com](http://docs.rancher-desktop.com/) that are broken with the current UI change.
- [ ] Allow the UI to be enabled with our existing pattern using the feature flags.
- [ ] Add support for [redirection rules](https://github.com/sorz/moproxy/blob/master/conf/policy.rules) (similar to `NOPROXY` env var)

### Proposed Solution

The following PR is meant to add to the core of the problem, however, there will be some outstanding items as mentioned above. 

### Additional Information

# Release notes
TBD

# Documentation
TBD

**Comment by tperale** [comment]
_McAfee Web Gateway_ proxy users are running into a certificate issue when forwarding the rancher-desktop WSL traffic to their proxy with the help of `moproxy`.

When running a `docker pull` they would get an _"Common Name Mismatch"_ error from the proxy.

```
Common Name Mismatch.
The certifiate verification failed due to a common name mismatch.

 Host: hub.docker.com
 Common name: *.docker.com
 Alternative subject names: regex([^.]*\.docker\.com), regex(dockercon\.com), regex(docker\.com), regex([^.]*\.docs\.docker\.com), regex(docs\.docker\.com), regex(docker\.io), regex([^.]*\.docker\.io), regex([^.]*\.dockercon\.com) 
```

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/4118134/2cad6245-06ea-47da-b3d4-5d9e352f5b6d)

`McAfee Web Gateway` users are not running into this issue when defining the `http_proxy` environment variables like documented on this issue https://github.com/rancher-sandbox/rancher-desktop/issues/4289
Connecting to a proxy with the `http_proxy` variable is different than with the help of `moproxy`. You don't use `HTTP CONNECT` and just forward the traffic to the proxy address.

I should work on adding the possibility to use this method to forward traffic to the proxy to `moproxy`.

**Comment by jandubois** [comment]
> I should work on adding the possibility to use this method to forward traffic to the proxy to `moproxy`.

Thanks for putting all the work into this feature!

I think it would be good to get the existing code into a state where it can be merged and made available as an experimental setting. And then issues can be resolved incrementally by additional PRs.

**Comment by tperale** [comment]
Thank you for your comment @jandubois, I've been discussing about getting the PR ready with @Nino-K on Slack. The PR is now ready to be merged. I use this "Epic" to sketches the roadmap for the next steps I need to work on in the coming weeks.
