### ISSUE TITLE
Epic: Locked fields in UI

### ISSUE THREAD

**Issue by s0nea** [rancher-sandbox/rancher-desktop#4662]
It is already possible to lock fields on the Preferences -> Container Engine -> Allowed Images tab.

The deployment profiles are generalizing this approach and allow the administrator to lock any preference field. This needs to be reflected by the UI.

## Stories

* [x] https://github.com/rancher-sandbox/rancher-desktop/issues/3959
* [x] #4689 (wrapper component)
* [x] #4795
* [x] #4700 (wrapper component)
* [x] #4771
* [x] #4723
* [x] #4707 (wrapper component)
* [x] #4772
* [x] #4815
* [x] #4709 (wrapper component)
* [x] ~~#4797~~
* [x] #4816
* [x] #4761
* [x] ~~The string-list for the patterns on Preferences -> Container Engine -> Allowed Images tab doesn't show the lock icon?~~
* [x] #4664
* [x] #4593
* [x] #4784

### Checkbox

- [ ] When locked, the checkbox should be disabled and display a lock icon next to its label.
- [ ] The checkbox should retain its current value when locked.
- [ ] The locked state should be visually indicated using appropriate CSS styles.

### Radio Group/Buttons

- [ ] When locked, all radio buttons in the group should be disabled and display an icon next to the group label.
- [ ] The correct active value should be selected when the radio group is locked.
- [ ] The locked state should be visually indicated using appropriate CSS styles.

### Select (Dropdown)

- [ ] When locked, the select element should be disabled and display a lock icon.
- [ ] The select should display the correct value when locked.
- [ ] The locked state should be visually indicated using appropriate CSS styles.

### Text or Number Input

- [ ] When locked, the input should be disabled and display a lock icon.
- [ ] The input should display the correct value when locked.
- [ ] The locked state should be visually indicated using appropriate CSS styles.

### Slider

- [ ] When locked, both the text box and the slider should be disabled, and a lock icon should be displayed next to the group label.
- [ ] The text box should display the correct value, and the slider should reflect the active value when locked.
- [ ] The locked state should be visually indicated using appropriate CSS styles.

### Lock Icon

- [ ] The lock icon should display a message on mouseover that provides a brief description of why the input is locked.
