### ISSUE TITLE
Epic: Automate deployment profile tests via BATS

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#4962]
This epic aims to automate all the test cases related to deployment profiles

### Acceptance Criteria:

- Use case 1: system profile and existing settings.json. Expected Output: override only locked properties from system profile, and preserve the remaining properties from settings.json
- Use case 2: system profile and user profile existing settings.json. Expected Output: If there is a system profile, user profile is just ignored. Overrides only locked properties from system profile, and preserve the remaining properties from settings.json
- Use case 3: No profiles and no settings. Json (fresh install). Expected Output: pops-up first-run dialog requesting settings and populate them in settings.json
- Use case 4: System profile, user profile and no settings.json. Expected Output: settings.json will be populated with settings from system profile. User profile will just be ignored.
- Use case 5: Only user profile and no settings. Expected Output: settings.json will be populated with settings from user profile.
- Use case 6: user profile and settings.json. Expected Output: override only locked properties from user profile, and preserve the remaining properties from settings.json
- Use case 7: corrupted system/user profile. Expected Output: System will pop-up an error dialog explicating the profiles have invalid format and will prevent the application to start.
- Use case 8: system profile with incorrect locked property and conflicting settings.json. 
- Use case 9: Start Rancher Desktop w/ deployment profiles with non-existing settings
- Use case 10: Start Rancher Desktop with deployment profiles containing wrong data types

#### Windows

 - [ ] Start Rancher Desktop with SYSTEM deployment profiles, no settings.json #4984 
 - [ ] SYSTEM profile and existing settings.json
 - [ ] SYSTEM profile and USER profile existing settings.json
 - [ ] SYSTEM profile and USER profile, no existing settings.json
 - [ ] Start Rancher Desktop with USER deployment profiles only
 - [ ] Start Rancher Desktop w/ deployment profiles with non-existing settings
 - [ ] Start Rancher Desktop with deployment profiles containing wrong data types
 - [ ] Start Rancher Desktop w/ bad-formatted deployment profiles 
 - [ ] SYSTEM profile with incorrect locked property and conflicting existing settings.json.
 - [ ] e2e tests for deployment profiles (integration with UI) - Different epic

#### macOS

 - [ ] Start Rancher Desktop with SYSTEM deployment profiles, no settings.json
 - [ ] SYSTEM profile and existing settings.json
 - [ ] SYSTEM profile and USER profile existing settings.json
 - [ ] SYSTEM profile and USER profile, no existing settings.json
 - [ ] Start Rancher Desktop with USER deployment profiles only
 - [ ] Start Rancher Desktop w/ deployment profiles with non-existing settings
 - [ ] Start Rancher Desktop with deployment profiles containing wrong data types
 - [ ] Start Rancher Desktop w/ bad-formatted deployment profiles 
 - [ ] SYSTEM profile with incorrect locked property and conflicting existing settings.json.
 - [ ] e2e tests for deployment profiles (integration with UI) - Different epic

#### Linux

 - [ ] Start Rancher Desktop with SYSTEM deployment profiles, no settings.json
 - [ ] SYSTEM profile and existing settings.json
 - [ ] SYSTEM profile and USER profile existing settings.json
 - [ ] SYSTEM profile and USER profile, no existing settings.json
 - [ ] Start Rancher Desktop with USER deployment profiles only
 - [ ] Start Rancher Desktop w/ deployment profiles with non-existing settings
 - [ ] Start Rancher Desktop with deployment profiles containing wrong data types
 - [ ] Start Rancher Desktop w/ bad-formatted deployment profiles 
 - [ ] SYSTEM profile with incorrect locked property and conflicting existing settings.json.
 - [ ] e2e tests for deployment profiles (integration with UI) - Different epic

**Comment by IsaSih** [comment]
#Creating individual issues to automate each test case described in #3753
