### ISSUE TITLE
Epic: Write bats tests that target networking scenarios

### ISSUE THREAD

**Issue by Nino-K** [rancher-sandbox/rancher-desktop#5185]
This issue aims to write/improve existing bats tests that cover our networking scenarios, port forwarding, k8s services, traefik, etc. These tests should be able to run on both default and our new networking stack. 

- [x] https://github.com/rancher-sandbox/rancher-desktop/pull/5212
- [x] https://github.com/rancher-sandbox/rancher-desktop/pull/5175
- [x] https://github.com/rancher-sandbox/rancher-desktop/pull/5168
- [x] https://github.com/rancher-sandbox/rancher-desktop/pull/5152
- [x] https://github.com/rancher-sandbox/rancher-desktop/pull/5151
- [x] https://github.com/rancher-sandbox/rancher-desktop/pull/5374
