### ISSUE TITLE
Epic: Create debug option to enable extended logging

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#538]
I would like a way for users to enable debug level logging for troubleshooting.

In addition to doing more logging itself, RD should also call subprocesses with verbose logging options, e.g. call `limactl --debug` instead of `limactl`.

To Do:

- [x] enable setting debug mode from GUI
- [x] add debug logging in main process
- [x] add debug logging in renderer process
- [x] ensure `--debug` is enabled on all `limactl` invocations
- [ ] enable debug level logging on WSL if possible
- [ ] enable debug level logging on everything else
- [x] print all `limactl` invocations to a log file when in debug mode

**Comment by jandubois** [comment]
Please also add a console to the VM (via `lima.yaml`) when running in debug mode:

```yaml
video:
  display: cocoa
```

Opening the console has some [negative side-effects](https://gitlab.com/qemu-project/qemu/-/issues/334), but I think is worth it for debugging purposes.

**Comment by gaktive** [comment]
@ericpromislow & @jandubois can provide updates on what to focus on first.

**Comment by adamkpickering** [comment]
To Do:

- [ ] enable setting debug mode from GUI
- [ ] add debug logging in main process
- [ ] add debug logging in renderer process
- [ ] ensure `--debug` is enabled on all `limactl` invocations
- [ ] enable debug level logging on WSL if possible
- [ ] enable debug level logging on k3s, nerdctl, docker and other things that run inside the lima/WSL VM
