### ISSUE TITLE
Epic: Containers Page: Follow-up

### ISSUE THREAD

**Issue by scures** [rancher-sandbox/rancher-desktop#5841]
Continuing the work from #4506

## Pending explorations:
- Created & Exited labels differences, we need to find a way to differentiate them better. 
- Explore if we should remove icons from the  `Start`, `Stop` & `Delete` buttons
- Check what happens with the containers list when you switch between d engines (to containerd) (add to list all namespaces) 
- We should have a manual refresh button on top of the list
- Check what happens with the Ports when containers are exposed but not as part of (@jandubois I think I cut this text and I couldn't find the whole sentence in the notes, can you remember what it was about?)

## Related Issues ∫ FE  :
- [x] https://github.com/rancher-sandbox/rancher-desktop/issues/5714 
- [x] https://github.com/rancher-sandbox/rancher-desktop/issues/5759
- [x] https://github.com/rancher-sandbox/rancher-desktop/issues/5775
- [x] #5893

## Later:
- [x] https://github.com/rancher-sandbox/rancher-desktop/issues/5308

## Resources:
Initial design: https://xd.adobe.com/view/801c1f95-6722-4d83-8a43-a596bba30743-d54f/
DockerDesktopClient: https://docs.docker.com/desktop/extensions-sdk/dev/api/reference/interfaces/DockerDesktopClient/

**Comment by rak-phillip** [comment]
@scures @jandubois it looks like we lost information regarding "View container details" from the original epic. Should that be included here or do we need to create a new issue to focus on this?

**Comment by jandubois** [comment]
> Should that be included here or do we need to create a new issue to focus on this?

Everything needed to work on this epic should be included in here. Eventually the work should be broken out into individual stories. I'll leave it to @scures how he would like to organize the work.

**Comment by jandubois** [comment]
I think there is no useful information left in this epic.
