### ISSUE TITLE
Epic: Kubeconfig in WSL should be a symlink to the host file

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#6245]
In Rancher Desktop 1.11 we converted `~/.kube/config` inside WSL distros with Rancher Desktop integration enabled from symlinks into separate files.

This was done because with the network tunneling feature enabled (which will soon become the default setting) the Kubernetes API is no longer available on `localhost` but only through a gateway interface. This is the case because Rancher Desktop is running in a separate network namespace from the rest of the distros (which all run in a shared network namespace).

This change has been problematic:

* the "Kubernetes Context" menu in the notification icon no longer reflects or changes the context inside WSL distros
* users with additional contexts can no longer maintain them in a single file but have to copy them manually into WSL config files

## Tasks

* [ ] Create a proxy exposing the API server on `127.0.0.1:6443` in the shared namespace
* [ ] Use a symlink for kubeconfig inside WSL distros
* [ ] Convert existing WSL kubeconfig back into a symlink, when possible
* [ ] Create diagnostics for WSL kubeconfig files that cannot be converted into symlinks

## Convert a WSL kubeconfig into a symlink

This is only possible when the file contains only the `rancher-desktop` context, but nothing else (or is empty). In that case we can simply delete the existing file, and it will be recreated as a symlink to the host file.

In all other cases we will have to update the kubeconfig inside the WSL distro in the same way as we do in Rancher Desktop 1.11. But we should also trigger a diagnostic to inform the user. There should be a separate diagnostic for each distro that has WSL integration enabled.
