### ISSUE TITLE
Epic: Improve Wasm feature

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#6622]
# Tasks

- [ ] Install additional shims when Wasm support is enabled

# Additional tasks (maybe later milestone)

- [ ] Diagnostic for "hidden" images when switching snapshotters
- [ ] Figure out why Wasm doesn't work with nerdctl
- [ ] Figure out if Wasm can be made to work with cri-dockerd and k3s
- [ ] Why don't we always use the containerd snapshotter with moby (at first-run/after factory reset)?
- [ ] Add tutorial for whole Wasm app lifecycle: Turning an app into a container

**Comment by linghengqian** [comment]
> Why don't we always use the containerd snapshotter with moby (at first-run/after factory reset)?

- There is an issue in moby that will set containerd-snapshotter as the default. See https://github.com/moby/moby/issues/49872 . Changes are expected to be applied in docker engine 29.0.0.

**Comment by linghengqian** [comment]
> > Why don't we always use the containerd snapshotter with moby (at first-run/after factory reset)?
> 
> * There is an issue in moby that will set containerd-snapshotter as the default. See [containerd snapshotters as default image backend moby/moby#49872](https://github.com/moby/moby/issues/49872) . Changes are expected to be applied in docker engine 29.0.0.

With the merge of https://github.com/moby/moby/pull/48009, https://github.com/moby/moby/issues/49872 was resolved in `Docker Engine 29.0.0` and documented in https://docs.docker.com/engine/release-notes/29/#2900 .

> containerd image store is now the default for fresh installs. This doesn't apply to daemons configured with userns-remap (see [moby#47377](https://github.com/moby/moby/issues/47377)).

The Alpine `3.23.0` containing this change has been released, see https://alpinelinux.org/posts/Alpine-3.23.0-released.html and https://pkgs.alpinelinux.org/packages?name=docker&branch=v3.23&repo=&arch=x86_64&origin=&flagged=&maintainer= . Now the issue becomes, when will `Rancher Desktop` update Alpine WSL version to `v3.23`? Once we do this, we don't need to define the following defaults in `\\wsl.localhost\rancher-desktop\etc\docker\daemon.json`. Do we need to open a new issue, similar to https://github.com/rancher-sandbox/rancher-desktop/issues/9321 or https://github.com/rancher-sandbox/rancher-desktop-wsl-distro/pull/135 ?

```json
{
  "features": {
    "containerd-snapshotter": true
  }
}

```

**Comment by jandubois** [comment]
> Do we need to open a new issue, similar to [#9321](https://github.com/rancher-sandbox/rancher-desktop/issues/9321) or [rancher-sandbox/rancher-desktop-wsl-distro#135](https://github.com/rancher-sandbox/rancher-desktop-wsl-distro/pull/135) ?

No, Rancher Desktop 1.21 already implements this functionality by itself, even with Docker 28.

**Comment by linghengqian** [comment]
Any Docker employees who have looked at https://github.com/docker/roadmap/issues/882 have remained silent... Whether WASM will remain in Docker Engine is truly questionable.
