### ISSUE TITLE
Epic: make sure all dependencies are built for arm64 on Linux and Windows

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#6623]
This Epic is on a milestone just for visibility; it is not a prerequisite for shipping the milestone.

Even if we don't ship Rancher Desktop for arm64 on Linux and Windows, it should still be easy for contributors to build it themselves. Which will be much easier if all dependencies are already available compiled for arm64.

## Third party

- [ ] https://github.com/rancher-sandbox/rancher-desktop-docker-cli/pull/9
- [ ] docker-buildx
- [ ] docker-compose
- [ ] ecr credential helpers
- [ ] helm
- [ ] kuberlr
- [ ] trivy
- [ ] Lima for Linux
- [ ] QEMU for Linux

## Rancher Desktop components

- [ ] steve
- [ ] Rancher Dashboard
- [ ] Guest Agent for Windows
- [ ] Host Resolver for Windows
- [ ] Host Switch for Windows

## Support

- [ ] Update preinstall script to fetch assets for arm64 on Linux and Windows
