### ISSUE TITLE
Epic: Create a manifest of all dependencies

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#6700]
We publish the list of bundled utilities in the [documentation](https://docs.rancherdesktop.io/references/bundled-utilities) and at the bottom of the release notes. This is manually generated for each release from [dependencies.yaml](https://github.com/rancher-sandbox/rancher-desktop/blob/main/pkg/rancher-desktop/assets/dependencies.yaml).

It is also missing information from tools packaged as part of `alpine-lima` or `wsl-distro`. It would be good to include the versions of `nerdctl`, `cri-dockerd`, `dockerd`, `containerd`, and `runc`, and possibly others.

In https://github.com/rancher-sandbox/rancher-desktop-wsl-distro/pull/90 we implemented [versions.env](https://github.com/rancher-sandbox/rancher-desktop-wsl-distro/blob/main/versions.env), which lists additional versions (but does not include packages installed from the Alpine repo, like `containerd`).

It would be nice to include this version manifest (augmented with the alpine package versions) as part of the `alpine-lima` and `wsl-distro` releases, so we could include the information within Rancher Desktop, and then create an `rdctl` subcommand to display it.

Ideally/long term we would want to use [SPDX](https://spdx.dev) to be able to publish an SBOM for Rancher Desktop, but initially we can just publish our version lists to get started.

- [ ] Publish `versions.env` as part of `alpine-lima` and `wsl-distro`
- [ ] Fetch `versions.env` together with the iso or tarball and store in resources directory
- [ ] Create `rdctl` subcommand to display version info
- [ ] Update release automation to include version info in draft release text

We already have a mechanism to include the output of shell commands in the documentation (that's how most of the `rdctl` reference is generated), so that can be used to make sure the docs are updated.

### Later improvements

- [ ] Include select Alpine packages in the released `version.env` files
- [ ] Use SPDX format to enable SBOM creation for Rancher Desktop

### Open problem

The `rdctl` subcommand could only report on the platform specific packages, e.g. the macOS version doesn't "know" what is bundled in `wsl-distro`.

Ideally both distros should always be rebuild with identical dependency versions at the same time, but that cannot be guaranteed. Maybe part of the release automation should verify that all versions package the same prerequisites?
