### ISSUE TITLE
Epic: Additional wasm-support asset

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#6715]
The size of all the additional Wasm binaries (shims, spin CLI) is getting too large to add them all to the regular Rancher Desktop installer.

Instead they should be bundled into an optional assets that will be downloaded once Wasm support is enabled for the first time, similar how we download and cache k3s versions.

- [ ] Create wasm-support asset for spin shim and cli in the build scripts
- [ ] Install wasm-support asset when Wasm support is enabled
- [ ] Include additional shims in wasm-support asset
- [ ] Install additional shims from wasm-support asset
