### ISSUE TITLE
Epic: Audit GHA for compliance with SUSE policies

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#6982]
Actions that need to be replaced (or their workflows disabled):

* [x] actions-rs/cargo - moproxy
      (will go away with #4680)

* [x] actions-rs/install - moproxy
      (will go away with #4680)
* [x] #7028
      (move to `yarn lint`)
* [x] ncipollo/release-action - moproxy
      (will go away with #4680)
* [x] peaceiris/actions-gh-pages - dashboard
      (`docusaurus` workflow has been disabled)
* [x] #7036
* [x] #7037
* [x] wangyoucao577/go-release-action - rancher-desktop-host-resolver
      (will go away with #6971)

**Comment by jandubois** [comment]
I've used the following script to audit our use of GitHub actions. It ignores repos that have disabled all actions:

```bash
#!/usr/bin/env bash

set -o errexit -o nounset

tempdir=$(mktemp -d -t repos) || exit 1
pushd "$tempdir" >/dev/null

for repo in $(gh api /orgs/rancher-sandbox/teams/rancher-desktop/repos --jq '.[].full_name'); do
    enabled=$(gh api "/repos/${repo}/actions/permissions" --jq '.enabled')
    if [[ $enabled == true ]]; then
        echo "$repo"
        git clone --quiet "git@github.com:${repo}"
    else
        echo "${repo} [DISABLED]"
    fi
done

perl <(cat <<'EOF'
use v5.20;
my %action;
while (<>) {
  my($repo) = $ARGV =~ m#^(?:\./)?([^/]+)#;
  next unless /^\s*-?\s*uses:\s+([^@\n]+)/;
  $action{$1}{$repo}++;
}
for my $action (sort keys %action) {
  say "\n$action";
  say "    $_" for sort keys %{$action{$action}};
}
EOF
) ./**/.github/workflows/*

popd >/dev/null
rm -rf "${tempdir:?}"
```

The output right now is

```
$ ./gha.sh
rancher-sandbox/alpine-lima
rancher-sandbox/bats-assert [DISABLED]
rancher-sandbox/bats-core [DISABLED]
rancher-sandbox/bats-file [DISABLED]
rancher-sandbox/bats-support [DISABLED]
rancher-sandbox/boot2tcl [DISABLED]
rancher-sandbox/cri-dockerd
rancher-sandbox/dashboard
rancher-sandbox/docker-machine-driver-hyperkit [DISABLED]
rancher-sandbox/docs.rancherdesktop.io
rancher-sandbox/epinio-desktop-extension
rancher-sandbox/lima
rancher-sandbox/lima-and-qemu
rancher-sandbox/moproxy
rancher-sandbox/ngx_http_proxy_connect_module
rancher-sandbox/openresty-packaging
rancher-sandbox/rancher-desktop
rancher-sandbox/rancher-desktop-agent
rancher-sandbox/rancher-desktop-docker-cli
rancher-sandbox/rancher-desktop-goproxy
rancher-sandbox/rancher-desktop-host-resolver
rancher-sandbox/rancher-desktop-lima
rancher-sandbox/rancher-desktop-networking
rancher-sandbox/rancher-desktop-steve
rancher-sandbox/rancher-desktop-upgrade-responder
rancher-sandbox/rancher-desktop-wsl-distro
rancher-sandbox/rancherdesktop.io

./.github/actions/setup-environment
    rancher-desktop

./.github/workflows/paths-ignore.yaml
    rancher-desktop

actions-rs/cargo
    moproxy

actions-rs/install
    moproxy

actions/cache
    lima

actions/checkout
    alpine-lima
    cri-dockerd
    dashboard
    docs.rancherdesktop.io
    epinio-desktop-extension
    lima
    lima-and-qemu
    moproxy
    ngx_http_proxy_connect_module
    rancher-desktop
    rancher-desktop-agent
    rancher-desktop-docker-cli
    rancher-desktop-goproxy
    rancher-desktop-host-resolver
    rancher-desktop-lima
    rancher-desktop-networking
    rancher-desktop-steve
    rancher-desktop-upgrade-responder
    rancher-desktop-wsl-distro
    rancherdesktop.io

actions/create-github-app-token
    rancher-desktop-wsl-distro

actions/deploy-pages
    docs.rancherdesktop.io
    rancherdesktop.io

actions/download-artifact
    dashboard
    lima
    lima-and-qemu
    rancher-desktop
    rancher-desktop-agent
    rancher-desktop-goproxy
    rancher-desktop-lima
    rancher-desktop-networking
    rancher-desktop-wsl-distro

actions/setup-go
    cri-dockerd
    lima
    lima-and-qemu
    rancher-desktop
    rancher-desktop-agent
    rancher-desktop-goproxy
    rancher-desktop-host-resolver
    rancher-desktop-lima
    rancher-desktop-networking
    rancher-desktop-steve
    rancher-desktop-upgrade-responder

actions/setup-node
    dashboard
    docs.rancherdesktop.io
    epinio-desktop-extension
    rancher-desktop
    rancherdesktop.io

actions/setup-python
    rancher-desktop

actions/upload-artifact
    cri-dockerd
    dashboard
    lima
    lima-and-qemu
    rancher-desktop
    rancher-desktop-agent
    rancher-desktop-docker-cli
    rancher-desktop-goproxy
    rancher-desktop-lima
    rancher-desktop-networking
    rancher-desktop-steve
    rancher-desktop-wsl-distro

actions/upload-pages-artifact
    docs.rancherdesktop.io
    rancherdesktop.io

check-spelling/check-spelling
    rancher-desktop

codecov/codecov-action
    dashboard

docker/bake-action
    rancher-desktop-docker-cli

docker/build-push-action
    epinio-desktop-extension
    rancher-desktop
    rancher-desktop-upgrade-responder

docker/login-action
    epinio-desktop-extension
    rancher-desktop
    rancher-desktop-upgrade-responder

docker/metadata-action
    rancher-desktop

docker/setup-buildx-action
    epinio-desktop-extension
    rancher-desktop
    rancher-desktop-docker-cli

docker/setup-qemu-action
    epinio-desktop-extension
    rancher-desktop

docker://dkhamsing/awesome_bot:latest
    lima

golangci/golangci-lint-action
    lima
    rancher-desktop
    rancher-desktop-agent
    rancher-desktop-host-resolver
    rancher-desktop-networking

ncipollo/release-action
    moproxy

nick-invision/retry
    lima

peaceiris/actions-gh-pages
    dashboard

prewk/s3-cp-action
    rancher-desktop

rancher-eio/read-vault-secrets
    rancher-desktop-wsl-distro

svenstaro/upload-release-action
    rancher-desktop-steve

updatecli/updatecli-action
    epinio-desktop-extension

wangyoucao577/go-release-action
    cri-dockerd
    rancher-desktop-host-resolver
```

**Comment by jandubois** [comment]
After checking against the current policy, I believe the following actions are problematic:

```
actions-rs/cargo
    moproxy

actions-rs/install
    moproxy

check-spelling/check-spelling
    rancher-desktop

ncipollo/release-action
    moproxy

peaceiris/actions-gh-pages
    dashboard

prewk/s3-cp-action
    rancher-desktop

svenstaro/upload-release-action
    rancher-desktop-steve

wangyoucao577/go-release-action
    rancher-desktop-host-resolver
```

**Comment by mook-as** [comment]
Re-checking at this point, the new output is:

<details>
<summary>Full script output</summary>

```
rancher-sandbox/rancher-desktop
rancher-sandbox/docker-machine-driver-hyperkit [ARCHIVED]
rancher-sandbox/rancher-desktop-wsl-distro
rancher-sandbox/boot2tcl [ARCHIVED]
rancher-sandbox/rancherdesktop.io
rancher-sandbox/lima [DISABLED]
rancher-sandbox/lima-and-qemu
rancher-sandbox/rancher-desktop-agent [ARCHIVED]
rancher-sandbox/rancher-desktop-docker-cli
rancher-sandbox/docs.rancherdesktop.io
rancher-sandbox/dashboard [ARCHIVED]
rancher-sandbox/rancher-desktop-steve
rancher-sandbox/rancher-desktop-host-resolver [ARCHIVED]
rancher-sandbox/cri-dockerd [DISABLED]
rancher-sandbox/bats-core [DISABLED]
rancher-sandbox/bats-assert [DISABLED]
rancher-sandbox/bats-support [DISABLED]
rancher-sandbox/openresty-packaging
rancher-sandbox/alpine-lima
rancher-sandbox/ngx_http_proxy_connect_module
rancher-sandbox/rancher-desktop-networking [ARCHIVED]
rancher-sandbox/bats-file [DISABLED]
rancher-sandbox/rancher-desktop-upgrade-responder
rancher-sandbox/epinio-desktop-extension [ARCHIVED]
rancher-sandbox/moproxy [ARCHIVED]
rancher-sandbox/rancher-desktop-goproxy
rancher-sandbox/rancher-desktop-lima
rancher-sandbox/rancher-desktop-rc
rancher-sandbox/rancher-desktop-qemu
rancher-sandbox/rancher-desktop-twocows

./.github/actions/get-token
    rancher-desktop

./.github/actions/setup-environment
    rancher-desktop

./.github/actions/yarn-install
    rancher-desktop

./.github/workflows/package.yaml
    openresty-packaging

./.github/workflows/paths-ignore.yaml
    rancher-desktop

actions/checkout
    alpine-lima
    docs.rancherdesktop.io
    lima-and-qemu
    ngx_http_proxy_connect_module
    openresty-packaging
    rancher-desktop
    rancher-desktop-docker-cli
    rancher-desktop-goproxy
    rancher-desktop-lima
    rancher-desktop-qemu
    rancher-desktop-steve
    rancher-desktop-twocows
    rancher-desktop-upgrade-responder
    rancher-desktop-wsl-distro
    rancherdesktop.io

actions/create-github-app-token
    rancher-desktop
    rancher-desktop-wsl-distro

actions/deploy-pages
    docs.rancherdesktop.io
    openresty-packaging
    rancherdesktop.io

actions/download-artifact
    lima-and-qemu
    openresty-packaging
    rancher-desktop
    rancher-desktop-goproxy
    rancher-desktop-lima
    rancher-desktop-qemu
    rancher-desktop-twocows
    rancher-desktop-wsl-distro

actions/setup-go
    lima-and-qemu
    rancher-desktop
    rancher-desktop-goproxy
    rancher-desktop-lima
    rancher-desktop-steve
    rancher-desktop-upgrade-responder

actions/setup-node
    docs.rancherdesktop.io
    rancher-desktop
    rancherdesktop.io

actions/setup-python
    rancher-desktop

actions/upload-artifact
    lima-and-qemu
    openresty-packaging
    rancher-desktop
    rancher-desktop-docker-cli
    rancher-desktop-goproxy
    rancher-desktop-lima
    rancher-desktop-qemu
    rancher-desktop-steve
    rancher-desktop-twocows
    rancher-desktop-wsl-distro

actions/upload-pages-artifact
    docs.rancherdesktop.io
    openresty-packaging
    rancherdesktop.io

docker/bake-action
    rancher-desktop-docker-cli

docker/build-push-action
    rancher-desktop
    rancher-desktop-upgrade-responder

docker/login-action
    rancher-desktop
    rancher-desktop-twocows
    rancher-desktop-upgrade-responder

docker/metadata-action
    rancher-desktop
    rancher-desktop-twocows

docker/setup-buildx-action
    openresty-packaging
    rancher-desktop
    rancher-desktop-docker-cli
    rancher-desktop-twocows

docker/setup-qemu-action
    openresty-packaging
    rancher-desktop
    rancher-desktop-twocows

github/codeql-action/analyze
    rancher-desktop

github/codeql-action/init
    rancher-desktop

github/codeql-action/upload-sarif
    rancher-desktop

ossf/scorecard-action
    rancher-desktop

rancher-eio/read-vault-secrets
    rancher-desktop
    rancher-desktop-wsl-distro

svenstaro/upload-release-action
    rancher-desktop-steve
```
</details>

Filtering out local actions, plus `actions/*`, `docker/*`, `github/*` we have:

```
# This is whitelisted
ossf/scorecard-action
    rancher-desktop

# rancher-eio/* is whitelisted
rancher-eio/read-vault-secrets
    rancher-desktop-wsl-distro

svenstaro/upload-release-action
    rancher-desktop-steve
```

So we still only have `svenstaro/upload-release-action` that needs attention.

<details>
<summary>Updated script to do minimal checkout</summary>

```sh
#!/usr/bin/env bash

set -o errexit -o nounset

tempdir=$(mktemp -d -t repos.XXXXXXX) || exit 1
pushd "$tempdir" >/dev/null
trap "rm -rf '${tempdir:?}'" EXIT

for repo in $(gh api /orgs/rancher-sandbox/teams/rancher-desktop/repos --jq '.[].full_name'); do
    if [[ "$(gh api "/repos/${repo}" --jq .archived)" == true ]]; then
      echo "${repo} [ARCHIVED]"
      continue
    fi
    enabled=$(gh api "/repos/${repo}/actions/permissions" --jq '.enabled')
    if [[ $enabled == true ]]; then
        echo "$repo"
        mkdir "${repo##*/}"
        git -C "${repo##*/}" init --quiet
        git -C "${repo##*/}" remote add origin "git@github.com:${repo}"
        git -C "${repo##*/}" sparse-checkout init --cone
        git -C "${repo##*/}" sparse-checkout add .github/workflows
        git -C "${repo##*/}" sparse-checkout add .github/actions
        git -C "${repo##*/}" fetch --quiet --depth=1 origin HEAD
        git -C "${repo##*/}" checkout --quiet FETCH_HEAD
    else
        echo "${repo} [DISABLED]"
    fi
done

perl <(cat <<'EOF'
use v5.20;
my %action;
while (<>) {
  my($repo) = $ARGV =~ m#^(?:\./)?([^/]+)#;
  next unless /^\s*-?\s*uses:\s+([^@\n]+)/;
  $action{$1}{$repo}++;
}
for my $action (sort keys %action) {
  say "\n$action";
  say "    $_" for sort keys %{$action{$action}};
}
EOF
) ./**/.github/workflows/* ./**/.github/actions/*/action.yaml

popd >/dev/null
```
</details>
