### ISSUE TITLE
Epic: Enable golangci-lint for all programs under src/go/*

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#7130]
We want to have a single `golangci-lint.yaml` file (maybe `.github/workflows/config/.golangci.yaml` right now?) that will be applied to all programs under `src/go`:

```console
$ ls -1 src/go
docker-credential-none
extension-proxy
github-runner-monitor
guestagent
mock-wsl
nerdctl-stub
networking
privileged-service
rdctl
vtunnel
wsl-helper
```

The only exceptions are `privileged-service` and `vtunnel`, as they should be deleted very soon.

Linting should be done via `yarn lint:go`, which already exists, but currently doesn't run `golangci-lint` (which needs to be documented as a new prerequisite in `README.md`).

At first most of the linters should be disabled, to get CI to pass.

Then we can enable one of the sub-linters at a time, and fix all the issues it complains about in all the repos. That way we can slowly add linters over time without breaking CI.

For `guestagent` and `networking` check the archived repos for the original linter configurations.

---

Tasks:

- [x] #7153
- [x] #7157
- [ ] golangci-lint: Evaluate original linters
- [ ] golangci-lint: Evaluate previous networking linters
- [ ] golangci-lint: Evaluate previous guest agent linters

**Comment by jandubois** [comment]
I don't think we need to keep this epic around. We can enable additional linters over time, as we feel fit, but there is no need to pay special attention to any particular linters, just because we used to enable them in a specific repo before.
