### ISSUE TITLE
Epic: Move dependencies from alpine-lima and wsl-distro into main repo

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#7136]
That way they will be covered by our `rddepman`, and we don't have to bump multiple modules to update them.

## Tasks

* [x] Merge rancher-desktop-agent → `src/go/guestagent`
* [x] Merge rancher-desktop-networking → `src/go/networking`
* [x] Build guestagent as part of `yarn postinstall`
* [ ] Add `guestagent` and `trivy` into `wsl-distro` tarball instead of installing at runtime
* [ ] Split `src/go/networking` into 3 components and build with `yarn postinstall`
* [ ] Add networking components to tarball and remove them from `rancher-desktop-wsl-distro`

## Later Milestone

* [ ] Add `nerdctl` and `cri_dockerd` to main repo packaging
* [ ] Add `rd-openresty` and `mkcert` Alpine packages to main repo packaging
* [ ] Switch to upstream version of `alpine-lima`

**Comment by Nino-K** [comment]
Since we are not building RD-Networking from the main repo, we had the following issue. As part of fixing the [issue](https://github.com/rancher-sandbox/rancher-desktop/issues/7331), we ended up creating this [release](https://github.com/rancher-sandbox/rancher-desktop-networking/releases/tag/v1.2.7). Therefore we should remember to re-import the RD-Networking repo again to avoid losing the latest changes. For now, I unchecked the `Merge rancher-desktop-networking → src/go/networking`.
